version: '3'
services:
  test_db:
    image: mysql:5.7
    container_name: test_db
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=local
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=local

  phpmyadmin_test:
    container_name: phpmyadmin_test
    depends_on:
      - test_db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8000:80'
    environment:
      PMA_HOST: test_db
      MYSQL_ROOT_PASSWORD: password