name: CI - Frontend

on: [pull_request]

defaults:
  run:
    working-directory: frontend

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

    - name: Install dependencies
      run: yarn

  lint:
    needs: [setup]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

    - name: Lint
      run: yarn lint
      
    # - name: Test
    #   run: yarn test
      
    # - name: Build
    #   run: yarn build
